"""initial hotel operations schema

Revision ID: 64853792b7f4
Revises: 
Create Date: 2026-09-28 10:23:12.633898
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '64853792b7f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=48), nullable=True),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_amenities')),
    sa.UniqueConstraint('code', name=op.f('uq_amenities_code'))
    )
    op.create_index(op.f('ix_amenities_created_at'), 'amenities', ['created_at'], unique=False)
    op.create_table('guests',
    sa.Column('reference', sa.String(length=24), nullable=False),
    sa.Column('first_name', sa.String(length=96), nullable=False),
    sa.Column('last_name', sa.String(length=96), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('alternate_phone', sa.String(length=32), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', 'undisclosed', name='gender', native_enum=False, length=32), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=64), nullable=True),
    sa.Column('address_line1', sa.String(length=180), nullable=True),
    sa.Column('address_line2', sa.String(length=180), nullable=True),
    sa.Column('city', sa.String(length=96), nullable=True),
    sa.Column('state', sa.String(length=96), nullable=True),
    sa.Column('postal_code', sa.String(length=24), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('id_document_type', sa.Enum('passport', 'national_id', 'drivers_license', 'residence_permit', 'other', name='id_document_type', native_enum=False, length=32), nullable=True),
    sa.Column('id_document_number', sa.String(length=64), nullable=True),
    sa.Column('id_document_expiry', sa.Date(), nullable=True),
    sa.Column('id_verified', sa.Boolean(), nullable=False),
    sa.Column('emergency_contact_name', sa.String(length=120), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=32), nullable=True),
    sa.Column('emergency_contact_relation', sa.String(length=48), nullable=True),
    sa.Column('company_name', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('preferences', sa.Text(), nullable=True),
    sa.Column('marketing_opt_in', sa.Boolean(), nullable=False),
    sa.Column('blacklisted', sa.Boolean(), nullable=False),
    sa.Column('blacklist_reason', sa.Text(), nullable=True),
    sa.Column('total_stays', sa.Integer(), nullable=False),
    sa.Column('total_nights', sa.Integer(), nullable=False),
    sa.Column('total_spend', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('outstanding_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('last_stay_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_vip', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_reason', sa.String(), nullable=True),
    sa.CheckConstraint('total_stays >= 0 AND total_nights >= 0', name=op.f('ck_guests_guest_counters_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guests'))
    )
    op.create_index(op.f('ix_guests_created_at'), 'guests', ['created_at'], unique=False)
    op.create_index('ix_guests_deleted', 'guests', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_guests_deleted_at'), 'guests', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_guests_email'), 'guests', ['email'], unique=False)
    op.create_index(op.f('ix_guests_first_name'), 'guests', ['first_name'], unique=False)
    op.create_index(op.f('ix_guests_last_name'), 'guests', ['last_name'], unique=False)
    op.create_index('ix_guests_name', 'guests', ['last_name', 'first_name'], unique=False)
    op.create_index(op.f('ix_guests_phone'), 'guests', ['phone'], unique=False)
    op.create_index(op.f('ix_guests_reference'), 'guests', ['reference'], unique=True)
    op.create_table('inventory_items',
    sa.Column('sku', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('supplier', sa.String(length=120), nullable=True),
    sa.Column('storage_location', sa.String(length=96), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_restocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_reason', sa.String(), nullable=True),
    sa.CheckConstraint('quantity_on_hand >= 0', name=op.f('ck_inventory_items_inventory_quantity_non_negative')),
    sa.CheckConstraint('reorder_level >= 0', name=op.f('ck_inventory_items_inventory_reorder_non_negative')),
    sa.CheckConstraint('unit_cost >= 0', name=op.f('ck_inventory_items_inventory_cost_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_items')),
    sa.UniqueConstraint('sku', name=op.f('uq_inventory_items_sku'))
    )
    op.create_index(op.f('ix_inventory_items_created_at'), 'inventory_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_items_deleted_at'), 'inventory_items', ['deleted_at'], unique=False)
    op.create_table('menu_categories',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kitchen_station', sa.String(length=48), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_menu_categories_name'))
    )
    op.create_index(op.f('ix_menu_categories_created_at'), 'menu_categories', ['created_at'], unique=False)
    op.create_table('payment_methods',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('cash', 'card', 'bank_transfer', 'mobile_money', 'other', name='payment_method_type', native_enum=False, length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('requires_reference', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_methods')),
    sa.UniqueConstraint('code', name=op.f('uq_payment_methods_code'))
    )
    op.create_index(op.f('ix_payment_methods_created_at'), 'payment_methods', ['created_at'], unique=False)
    op.create_table('permissions',
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('resource', sa.String(length=48), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('group_name', sa.String(length=48), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name='uq_permissions_code')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=False)
    op.create_index(op.f('ix_permissions_created_at'), 'permissions', ['created_at'], unique=False)
    op.create_table('roles',
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_reason', sa.String(), nullable=True),
    sa.CheckConstraint('level >= 0 AND level <= 100', name=op.f('ck_roles_role_level_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_roles_deleted_at'), 'roles', ['deleted_at'], unique=False)
    op.create_table('room_types',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('weekend_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('extra_person_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_occupancy', sa.Integer(), nullable=False),
    sa.Column('max_adults', sa.Integer(), nullable=False),
    sa.Column('max_children', sa.Integer(), nullable=False),
    sa.Column('bed_type', sa.Enum('single', 'double', 'queen', 'king', 'twin', 'sofa_bed', 'bunk', name='bed_type', native_enum=False, length=32), nullable=False),
    sa.Column('bed_count', sa.Integer(), nullable=False),
    sa.Column('size_sqm', sa.Integer(), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hero_image_url', sa.String(length=512), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_reason', sa.String(), nullable=True),
    sa.CheckConstraint('base_price >= 0', name=op.f('ck_room_types_room_type_base_price_non_negative')),
    sa.CheckConstraint('max_adults > 0 AND max_children >= 0', name=op.f('ck_room_types_room_type_guest_limits')),
    sa.CheckConstraint('max_occupancy > 0', name=op.f('ck_room_types_room_type_occupancy_positive')),
    sa.CheckConstraint('tax_rate >= 0 AND tax_rate <= 100', name=op.f('ck_room_types_room_type_tax_rate_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_types')),
    sa.UniqueConstraint('code', name=op.f('uq_room_types_code')),
    sa.UniqueConstraint('name', name=op.f('uq_room_types_name'))
    )
    op.create_index(op.f('ix_room_types_created_at'), 'room_types', ['created_at'], unique=False)
    op.create_index(op.f('ix_room_types_deleted_at'), 'room_types', ['deleted_at'], unique=False)
    op.create_table('services',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('availability', sa.Enum('always', 'scheduled', 'weekdays', 'weekends', 'on_request', name='service_availability', native_enum=False, length=32), nullable=False),
    sa.Column('available_from', sa.String(length=5), nullable=True),
    sa.Column('available_to', sa.String(length=5), nullable=True),
    sa.Column('requires_scheduling', sa.Boolean(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_taxable', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_reason', sa.String(), nullable=True),
    sa.CheckConstraint('price >= 0', name=op.f('ck_services_service_price_non_negative')),
    sa.CheckConstraint('tax_rate >= 0 AND tax_rate <= 100', name=op.f('ck_services_service_tax_rate_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services')),
    sa.UniqueConstraint('code', name=op.f('uq_services_code')),
    sa.UniqueConstraint('name', name=op.f('uq_services_name'))
    )
    op.create_index(op.f('ix_services_category'), 'services', ['category'], unique=False)
    op.create_index(op.f('ix_services_created_at'), 'services', ['created_at'], unique=False)
    op.create_index(op.f('ix_services_deleted_at'), 'services', ['deleted_at'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=96), nullable=False),
    sa.Column('last_name', sa.String(length=96), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('job_title', sa.String(length=96), nullable=True),
    sa.Column('employee_code', sa.String(length=32), nullable=True),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', 'pending', name='user_status', native_enum=False, length=32), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=64), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_reason', sa.String(), nullable=True),
    sa.CheckConstraint('failed_login_count >= 0', name=op.f('ck_users_user_failed_login_non_negative')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_users_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('employee_code', name=op.f('uq_users_employee_code'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_status_deleted', 'users', ['status', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('username', sa.String(length=96), nullable=True),
    sa.Column('user_role', sa.String(length=96), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('resource', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('before_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('extra_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_ip_address'), 'audit_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource'), 'audit_logs', ['resource'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index('ix_audit_resource_created', 'audit_logs', ['resource', 'created_at'], unique=False)
    op.create_index('ix_audit_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('expenses',
    sa.Column('expense_number', sa.String(length=24), nullable=False),
    sa.Column('category', sa.Enum('utilities', 'salaries', 'maintenance', 'supplies', 'food_beverage', 'transportation', 'marketing', 'taxes', 'other', name='expense_category', native_enum=False, length=32), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('payment_method_id', sa.Uuid(), nullable=True),
    sa.Column('payment_method_label', sa.String(length=64), nullable=True),
    sa.Column('vendor', sa.String(length=120), nullable=True),
    sa.Column('reference', sa.String(length=96), nullable=True),
    sa.Column('recorded_by_id', sa.Uuid(), nullable=True),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attachment_name', sa.String(length=180), nullable=True),
    sa.Column('attachment_path', sa.String(length=400), nullable=True),
    sa.Column('attachment_mime', sa.String(length=96), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_reason', sa.String(), nullable=True),
    sa.CheckConstraint('amount > 0', name=op.f('ck_expenses_expense_amount_positive')),
    sa.CheckConstraint('tax_amount >= 0', name=op.f('ck_expenses_expense_tax_non_negative')),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_expenses_approved_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], name=op.f('fk_expenses_payment_method_id_payment_methods'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], name=op.f('fk_expenses_recorded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_index(op.f('ix_expenses_category'), 'expenses', ['category'], unique=False)
    op.create_index(op.f('ix_expenses_created_at'), 'expenses', ['created_at'], unique=False)
    op.create_index('ix_expenses_date_category', 'expenses', ['expense_date', 'category'], unique=False)
    op.create_index(op.f('ix_expenses_deleted_at'), 'expenses', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_expenses_expense_date'), 'expenses', ['expense_date'], unique=False)
    op.create_index(op.f('ix_expenses_expense_number'), 'expenses', ['expense_number'], unique=True)
    op.create_table('hotel_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('group_name', sa.String(length=48), nullable=False),
    sa.Column('label', sa.String(length=96), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('editable', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_hotel_settings_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hotel_settings'))
    )
    op.create_index(op.f('ix_hotel_settings_created_at'), 'hotel_settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_hotel_settings_key'), 'hotel_settings', ['key'], unique=True)
    op.create_table('inventory_movements',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('delta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('resulting_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=48), nullable=False),
    sa.Column('reference', sa.String(length=96), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('resulting_quantity >= 0', name=op.f('ck_inventory_movements_inventory_result_non_negative')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_inventory_movements_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], name=op.f('fk_inventory_movements_item_id_inventory_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_movements'))
    )
    op.create_index(op.f('ix_inventory_movements_created_at'), 'inventory_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_movements_item_id'), 'inventory_movements', ['item_id'], unique=False)
    op.create_table('login_attempts',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('failure_reason', sa.String(length=96), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_login_attempts_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempts'))
    )
    op.create_index(op.f('ix_login_attempts_attempted_at'), 'login_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_created_at'), 'login_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_email'), 'login_attempts', ['email'], unique=False)
    op.create_table('menu_items',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sku', sa.String(length=32), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('prep_minutes', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_vegetarian', sa.Boolean(), nullable=False),
    sa.Column('is_vegan', sa.Boolean(), nullable=False),
    sa.Column('is_gluten_free', sa.Boolean(), nullable=False),
    sa.Column('spice_level', sa.Integer(), nullable=False),
    sa.Column('allergens', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_reason', sa.String(), nullable=True),
    sa.CheckConstraint('price >= 0', name=op.f('ck_menu_items_menu_item_price_non_negative')),
    sa.CheckConstraint('spice_level >= 0 AND spice_level <= 3', name=op.f('ck_menu_items_menu_item_spice_level_range')),
    sa.CheckConstraint('tax_rate >= 0 AND tax_rate <= 100', name=op.f('ck_menu_items_menu_item_tax_rate_range')),
    sa.ForeignKeyConstraint(['category_id'], ['menu_categories.id'], name=op.f('fk_menu_items_category_id_menu_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_items')),
    sa.UniqueConstraint('sku', name=op.f('uq_menu_items_sku'))
    )
    op.create_index(op.f('ix_menu_items_category_id'), 'menu_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_menu_items_created_at'), 'menu_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_menu_items_deleted_at'), 'menu_items', ['deleted_at'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('reservation', 'payment', 'housekeeping', 'maintenance', 'inventory', 'system', name='notification_category', native_enum=False, length=32), nullable=False),
    sa.Column('severity', sa.Enum('info', 'success', 'warning', 'critical', name='notification_severity', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('entity_type', sa.String(length=48), nullable=True),
    sa.Column('entity_id', sa.String(length=48), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_dedupe_key'), 'notifications', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read_created', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_ip', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens'))
    )
    op.create_index(op.f('ix_password_reset_tokens_created_at'), 'password_reset_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_jti', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('jti', name=op.f('uq_refresh_tokens_jti'))
    )
    op.create_index(op.f('ix_refresh_tokens_created_at'), 'refresh_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('room_type_amenities',
    sa.Column('room_type_id', sa.Uuid(), nullable=False),
    sa.Column('amenity_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], name=op.f('fk_room_type_amenities_amenity_id_amenities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], name=op.f('fk_room_type_amenities_room_type_id_room_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_type_id', 'amenity_id', name=op.f('pk_room_type_amenities'))
    )
    op.create_table('rooms',
    sa.Column('number', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=True),
    sa.Column('room_type_id', sa.Uuid(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(length=48), nullable=True),
    sa.Column('wing', sa.String(length=48), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('bed_type', sa.Enum('single', 'double', 'queen', 'king', 'twin', 'sofa_bed', 'bunk', name='room_bed_type', native_enum=False, length=32), nullable=False),
    sa.Column('bed_count', sa.Integer(), nullable=False),
    sa.Column('price_per_night', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('available', 'reserved', 'occupied', 'cleaning', 'maintenance', 'out_of_service', name='room_status', native_enum=False, length=32), nullable=False),
    sa.Column('housekeeping_condition', sa.Enum('clean', 'dirty', 'cleaning', 'inspected', name='housekeeping_condition', native_enum=False, length=32), nullable=False),
    sa.Column('maintenance_flag', sa.Enum('operational', 'needs_attention', 'under_maintenance', 'out_of_order', name='maintenance_flag', native_enum=False, length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('images', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('view', sa.String(length=48), nullable=True),
    sa.Column('is_smoking', sa.Boolean(), nullable=False),
    sa.Column('is_accessible', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_reason', sa.String(), nullable=True),
    sa.CheckConstraint('capacity > 0', name=op.f('ck_rooms_room_capacity_positive')),
    sa.CheckConstraint('floor >= 0', name=op.f('ck_rooms_room_floor_non_negative')),
    sa.CheckConstraint('price_per_night >= 0', name=op.f('ck_rooms_room_price_non_negative')),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], name=op.f('fk_rooms_room_type_id_room_types'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms'))
    )
    op.create_index(op.f('ix_rooms_created_at'), 'rooms', ['created_at'], unique=False)
    op.create_index(op.f('ix_rooms_deleted_at'), 'rooms', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_rooms_number'), 'rooms', ['number'], unique=True)
    op.create_index(op.f('ix_rooms_room_type_id'), 'rooms', ['room_type_id'], unique=False)
    op.create_index(op.f('ix_rooms_status'), 'rooms', ['status'], unique=False)
    op.create_index('ix_rooms_status_floor', 'rooms', ['status', 'floor'], unique=False)
    op.create_index('ix_rooms_type_active', 'rooms', ['room_type_id', 'is_active'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('reservations',
    sa.Column('reference', sa.String(length=24), nullable=False),
    sa.Column('guest_id', sa.Uuid(), nullable=False),
    sa.Column('room_type_id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=True),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('nights', sa.Integer(), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('children', sa.Integer(), nullable=False),
    sa.Column('room_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('extra_person_charge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('room_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('services_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('charges_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('refunded_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_reason', sa.String(length=180), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'checked_in', 'checked_out', 'cancelled', 'no_show', name='reservation_status', native_enum=False, length=32), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'partial', 'paid', 'refunded', 'failed', 'cancelled', name='reservation_payment_status', native_enum=False, length=32), nullable=False),
    sa.Column('folio_status', sa.Enum('open', 'closed', 'settled', name='folio_status', native_enum=False, length=32), nullable=False),
    sa.Column('booking_source', sa.Enum('walk_in', 'phone', 'email', 'website', 'ota', 'corporate', 'travel_agent', 'referral', name='booking_source', native_enum=False, length=32), nullable=False),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_id', sa.Uuid(), nullable=True),
    sa.Column('no_show_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('folio_closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_reason', sa.String(), nullable=True),
    sa.CheckConstraint('adults >= 1', name=op.f('ck_reservations_reservation_adults_min_one')),
    sa.CheckConstraint('check_out_date > check_in_date', name=op.f('ck_reservations_reservation_stay_window_valid')),
    sa.CheckConstraint('children >= 0', name=op.f('ck_reservations_reservation_children_non_negative')),
    sa.CheckConstraint('discount_amount >= 0', name=op.f('ck_reservations_reservation_discount_non_negative')),
    sa.CheckConstraint('nights > 0', name=op.f('ck_reservations_reservation_nights_positive')),
    sa.CheckConstraint('room_rate >= 0', name=op.f('ck_reservations_reservation_rate_non_negative')),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], name=op.f('fk_reservations_cancelled_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_reservations_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('fk_reservations_guest_id_guests'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_reservations_room_id_rooms'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], name=op.f('fk_reservations_room_type_id_room_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_reservations_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservations'))
    )
    op.create_index(op.f('ix_reservations_check_in_date'), 'reservations', ['check_in_date'], unique=False)
    op.create_index(op.f('ix_reservations_check_out_date'), 'reservations', ['check_out_date'], unique=False)
    op.create_index(op.f('ix_reservations_created_at'), 'reservations', ['created_at'], unique=False)
    op.create_index(op.f('ix_reservations_deleted_at'), 'reservations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_reservations_guest_id'), 'reservations', ['guest_id'], unique=False)
    op.create_index(op.f('ix_reservations_payment_status'), 'reservations', ['payment_status'], unique=False)
    op.create_index(op.f('ix_reservations_reference'), 'reservations', ['reference'], unique=True)
    op.create_index(op.f('ix_reservations_room_id'), 'reservations', ['room_id'], unique=False)
    op.create_index(op.f('ix_reservations_room_type_id'), 'reservations', ['room_type_id'], unique=False)
    op.create_index('ix_reservations_room_window', 'reservations', ['room_id', 'check_in_date', 'check_out_date'], unique=False)
    op.create_index(op.f('ix_reservations_status'), 'reservations', ['status'], unique=False)
    op.create_index('ix_reservations_status_window', 'reservations', ['status', 'check_in_date'], unique=False)
    op.create_table('room_amenity_links',
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('amenity_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], name=op.f('fk_room_amenity_links_amenity_id_amenities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_amenity_links_room_id_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'amenity_id', name=op.f('pk_room_amenity_links'))
    )
    op.create_table('check_ins',
    sa.Column('reservation_id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checked_in_by_id', sa.Uuid(), nullable=True),
    sa.Column('deposit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('identity_verified', sa.Boolean(), nullable=False),
    sa.Column('registration_card_signed', sa.Boolean(), nullable=False),
    sa.Column('key_cards_issued', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confirmation_code', sa.String(length=24), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checked_in_by_id'], ['users.id'], name=op.f('fk_check_ins_checked_in_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('fk_check_ins_reservation_id_reservations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_check_ins_room_id_rooms'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_check_ins')),
    sa.UniqueConstraint('reservation_id', name='check_in_reservation_unique')
    )
    op.create_index(op.f('ix_check_ins_created_at'), 'check_ins', ['created_at'], unique=False)
    op.create_index(op.f('ix_check_ins_reservation_id'), 'check_ins', ['reservation_id'], unique=False)
    op.create_table('check_outs',
    sa.Column('reservation_id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checked_out_by_id', sa.Uuid(), nullable=True),
    sa.Column('final_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance_settled', sa.Boolean(), nullable=False),
    sa.Column('override_by_id', sa.Uuid(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('keys_returned', sa.Boolean(), nullable=False),
    sa.Column('minibar_checked', sa.Boolean(), nullable=False),
    sa.Column('luggage_collected', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checked_out_by_id'], ['users.id'], name=op.f('fk_check_outs_checked_out_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['override_by_id'], ['users.id'], name=op.f('fk_check_outs_override_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('fk_check_outs_reservation_id_reservations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_check_outs_room_id_rooms'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_check_outs')),
    sa.UniqueConstraint('reservation_id', name='check_out_reservation_unique')
    )
    op.create_index(op.f('ix_check_outs_created_at'), 'check_outs', ['created_at'], unique=False)
    op.create_index(op.f('ix_check_outs_reservation_id'), 'check_outs', ['reservation_id'], unique=False)
    op.create_table('housekeeping_tasks',
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=True),
    sa.Column('task_type', sa.Enum('checkout_clean', 'stayover_clean', 'deep_clean', 'inspection', 'turndown', 'public_area', name='housekeeping_task_type', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'inspected', 'cancelled', name='housekeeping_task_status', native_enum=False, length=32), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='housekeeping_priority', native_enum=False, length=32), nullable=False),
    sa.Column('assigned_to_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('inspected_by_id', sa.Uuid(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.String(length=5), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inspected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('maintenance_reported', sa.Boolean(), nullable=False),
    sa.Column('damage_reported', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_housekeeping_tasks_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_housekeeping_tasks_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inspected_by_id'], ['users.id'], name=op.f('fk_housekeeping_tasks_inspected_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('fk_housekeeping_tasks_reservation_id_reservations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_housekeeping_tasks_room_id_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_housekeeping_tasks'))
    )
    op.create_index('ix_housekeeping_assignee_status', 'housekeeping_tasks', ['assigned_to_id', 'status'], unique=False)
    op.create_index('ix_housekeeping_status_date', 'housekeeping_tasks', ['status', 'scheduled_date'], unique=False)
    op.create_index(op.f('ix_housekeeping_tasks_assigned_to_id'), 'housekeeping_tasks', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_housekeeping_tasks_created_at'), 'housekeeping_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_housekeeping_tasks_room_id'), 'housekeeping_tasks', ['room_id'], unique=False)
    op.create_index(op.f('ix_housekeeping_tasks_scheduled_date'), 'housekeeping_tasks', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_housekeeping_tasks_status'), 'housekeeping_tasks', ['status'], unique=False)
    op.create_table('invoices',
    sa.Column('number', sa.String(length=24), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=False),
    sa.Column('guest_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'issued', 'partially_paid', 'paid', 'void', 'overdue', name='invoice_status', native_enum=False, length=32), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('guest_name', sa.String(length=180), nullable=False),
    sa.Column('guest_email', sa.String(length=255), nullable=True),
    sa.Column('guest_address', sa.Text(), nullable=True),
    sa.Column('guest_tax_id', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_receipt', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('issued_by_id', sa.Uuid(), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by_id', sa.Uuid(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_reason', sa.String(), nullable=True),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_invoices_invoice_total_non_negative')),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('fk_invoices_guest_id_guests'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], name=op.f('fk_invoices_issued_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('fk_invoices_reservation_id_reservations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voided_by_id'], ['users.id'], name=op.f('fk_invoices_voided_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    op.create_index(op.f('ix_invoices_created_at'), 'invoices', ['created_at'], unique=False)
    op.create_index(op.f('ix_invoices_deleted_at'), 'invoices', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_invoices_guest_id'), 'invoices', ['guest_id'], unique=False)
    op.create_index(op.f('ix_invoices_issue_date'), 'invoices', ['issue_date'], unique=False)
    op.create_index('ix_invoices_issue_status', 'invoices', ['issue_date', 'status'], unique=False)
    op.create_index(op.f('ix_invoices_number'), 'invoices', ['number'], unique=True)
    op.create_index(op.f('ix_invoices_reservation_id'), 'invoices', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('reservation_guests',
    sa.Column('reservation_id', sa.Uuid(), nullable=False),
    sa.Column('guest_id', sa.Uuid(), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('relationship_to_lead', sa.String(length=48), nullable=True),
    sa.Column('is_lead', sa.Boolean(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('id_document_number', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('age IS NULL OR age >= 0', name=op.f('ck_reservation_guests_reservation_guest_age_non_negative')),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('fk_reservation_guests_guest_id_guests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('fk_reservation_guests_reservation_id_reservations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservation_guests')),
    sa.UniqueConstraint('reservation_id', 'guest_id', name='reservation_guest_unique')
    )
    op.create_index(op.f('ix_reservation_guests_created_at'), 'reservation_guests', ['created_at'], unique=False)
    op.create_index(op.f('ix_reservation_guests_reservation_id'), 'reservation_guests', ['reservation_id'], unique=False)
    op.create_table('service_orders',
    sa.Column('order_number', sa.String(length=24), nullable=False),
    sa.Column('order_type', sa.Enum('room_service', 'restaurant', 'service', name='order_type', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'preparing', 'ready', 'delivered', 'cancelled', name='order_status', native_enum=False, length=32), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=True),
    sa.Column('guest_id', sa.Uuid(), nullable=True),
    sa.Column('room_id', sa.Uuid(), nullable=True),
    sa.Column('table_reference', sa.String(length=24), nullable=True),
    sa.Column('is_room_service', sa.Boolean(), nullable=False),
    sa.Column('is_billed', sa.Boolean(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('service_charge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('placed_by_id', sa.Uuid(), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_reason', sa.String(), nullable=True),
    sa.CheckConstraint('subtotal >= 0 AND tax_amount >= 0 AND total_amount >= 0', name=op.f('ck_service_orders_order_totals_non_negative')),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('fk_service_orders_guest_id_guests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['placed_by_id'], ['users.id'], name=op.f('fk_service_orders_placed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('fk_service_orders_reservation_id_reservations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_service_orders_room_id_rooms'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_orders'))
    )
    op.create_index(op.f('ix_service_orders_created_at'), 'service_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_service_orders_deleted_at'), 'service_orders', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_service_orders_is_billed'), 'service_orders', ['is_billed'], unique=False)
    op.create_index(op.f('ix_service_orders_order_number'), 'service_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_service_orders_order_type'), 'service_orders', ['order_type'], unique=False)
    op.create_index(op.f('ix_service_orders_placed_at'), 'service_orders', ['placed_at'], unique=False)
    op.create_index(op.f('ix_service_orders_reservation_id'), 'service_orders', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_service_orders_status'), 'service_orders', ['status'], unique=False)
    op.create_index('ix_service_orders_status_placed', 'service_orders', ['status', 'placed_at'], unique=False)
    op.create_table('maintenance_tickets',
    sa.Column('ticket_number', sa.String(length=24), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=True),
    sa.Column('location', sa.String(length=96), nullable=True),
    sa.Column('category', sa.Enum('plumbing', 'electrical', 'furniture', 'air_conditioning', 'internet', 'appliance', 'safety', 'other', name='maintenance_category', native_enum=False, length=32), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='maintenance_priority', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('open', 'assigned', 'in_progress', 'resolved', 'closed', name='maintenance_status', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reported_by_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_to_id', sa.Uuid(), nullable=True),
    sa.Column('related_task_id', sa.Uuid(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('blocks_room', sa.Boolean(), nullable=False),
    sa.Column('photo_urls', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cost >= 0', name=op.f('ck_maintenance_tickets_maintenance_cost_non_negative')),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_maintenance_tickets_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_task_id'], ['housekeeping_tasks.id'], name=op.f('fk_maintenance_tickets_related_task_id_housekeeping_tasks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], name=op.f('fk_maintenance_tickets_reported_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_maintenance_tickets_room_id_rooms'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_tickets'))
    )
    op.create_index('ix_maintenance_status_priority', 'maintenance_tickets', ['status', 'priority'], unique=False)
    op.create_index(op.f('ix_maintenance_tickets_assigned_to_id'), 'maintenance_tickets', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_maintenance_tickets_category'), 'maintenance_tickets', ['category'], unique=False)
    op.create_index(op.f('ix_maintenance_tickets_created_at'), 'maintenance_tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_maintenance_tickets_priority'), 'maintenance_tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_maintenance_tickets_reported_at'), 'maintenance_tickets', ['reported_at'], unique=False)
    op.create_index(op.f('ix_maintenance_tickets_room_id'), 'maintenance_tickets', ['room_id'], unique=False)
    op.create_index(op.f('ix_maintenance_tickets_status'), 'maintenance_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_maintenance_tickets_ticket_number'), 'maintenance_tickets', ['ticket_number'], unique=True)
    op.create_table('payments',
    sa.Column('number', sa.String(length=24), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=False),
    sa.Column('guest_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('parent_payment_id', sa.Uuid(), nullable=True),
    sa.Column('entry_type', sa.Enum('payment', 'refund', name='payment_entry_type', native_enum=False, length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('method_id', sa.Uuid(), nullable=True),
    sa.Column('method_code', sa.String(length=32), nullable=False),
    sa.Column('method_label', sa.String(length=64), nullable=False),
    sa.Column('reference', sa.String(length=96), nullable=True),
    sa.Column('status', sa.Enum('pending', 'partial', 'paid', 'refunded', 'failed', 'cancelled', name='payment_status', native_enum=False, length=32), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_by_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by_id', sa.Uuid(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_reason', sa.String(), nullable=True),
    sa.CheckConstraint("length(currency) = 3 AND currency = upper(currency)", name=op.f('ck_payments_payment_currency_format')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payments_payment_amount_positive')),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('fk_payments_guest_id_guests'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_payments_invoice_id_invoices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['method_id'], ['payment_methods.id'], name=op.f('fk_payments_method_id_payment_methods'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_payment_id'], ['payments.id'], name=op.f('fk_payments_parent_payment_id_payments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], name=op.f('fk_payments_received_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('fk_payments_reservation_id_reservations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voided_by_id'], ['users.id'], name=op.f('fk_payments_voided_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_deleted_at'), 'payments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_payments_entry_type'), 'payments', ['entry_type'], unique=False)
    op.create_index(op.f('ix_payments_guest_id'), 'payments', ['guest_id'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_number'), 'payments', ['number'], unique=True)
    op.create_index('ix_payments_paid_at', 'payments', ['paid_at'], unique=False)
    op.create_index('ix_payments_reservation_entry', 'payments', ['reservation_id', 'entry_type'], unique=False)
    op.create_index(op.f('ix_payments_reservation_id'), 'payments', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index('ix_payments_status_entry', 'payments', ['status', 'entry_type'], unique=False)
    op.create_table('reservation_charges',
    sa.Column('reservation_id', sa.Uuid(), nullable=False),
    sa.Column('charge_type', sa.Enum('room', 'service', 'restaurant', 'laundry', 'minibar', 'damage', 'discount', 'adjustment', 'other', name='charge_type', native_enum=False, length=32), nullable=False),
    sa.Column('description', sa.String(length=180), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('service_order_id', sa.Uuid(), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('is_voided', sa.Boolean(), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by_id', sa.Uuid(), nullable=True),
    sa.Column('void_reason', sa.String(length=180), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('posted_by_id', sa.Uuid(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount_amount >= 0', name=op.f('ck_reservation_charges_charge_discount_non_negative')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_reservation_charges_charge_quantity_positive')),
    sa.CheckConstraint('tax_rate >= 0 AND tax_rate <= 100', name=op.f('ck_reservation_charges_charge_tax_rate_range')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_reservation_charges_charge_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['posted_by_id'], ['users.id'], name=op.f('fk_reservation_charges_posted_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('fk_reservation_charges_reservation_id_reservations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], name=op.f('fk_reservation_charges_service_order_id_service_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voided_by_id'], ['users.id'], name=op.f('fk_reservation_charges_voided_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservation_charges'))
    )
    op.create_index(op.f('ix_reservation_charges_charge_type'), 'reservation_charges', ['charge_type'], unique=False)
    op.create_index(op.f('ix_reservation_charges_created_at'), 'reservation_charges', ['created_at'], unique=False)
    op.create_index(op.f('ix_reservation_charges_is_voided'), 'reservation_charges', ['is_voided'], unique=False)
    op.create_index(op.f('ix_reservation_charges_posted_at'), 'reservation_charges', ['posted_at'], unique=False)
    op.create_index(op.f('ix_reservation_charges_reservation_id'), 'reservation_charges', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_reservation_charges_service_date'), 'reservation_charges', ['service_date'], unique=False)
    op.create_table('service_order_items',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=True),
    sa.Column('menu_item_id', sa.Uuid(), nullable=True),
    sa.Column('name_snapshot', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_service_order_items_order_item_quantity_positive')),
    sa.CheckConstraint('service_id IS NOT NULL OR menu_item_id IS NOT NULL', name=op.f('ck_service_order_items_order_item_has_source')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_service_order_items_order_item_price_non_negative')),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('fk_service_order_items_menu_item_id_menu_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['service_orders.id'], name=op.f('fk_service_order_items_order_id_service_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_service_order_items_service_id_services'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_order_items'))
    )
    op.create_index(op.f('ix_service_order_items_created_at'), 'service_order_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_service_order_items_order_id'), 'service_order_items', ['order_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('charge_id', sa.Uuid(), nullable=True),
    sa.Column('charge_type', sa.Enum('room', 'service', 'restaurant', 'laundry', 'minibar', 'damage', 'discount', 'adjustment', 'other', name='invoice_item_charge_type', native_enum=False, length=32), nullable=False),
    sa.Column('description', sa.String(length=180), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['charge_id'], ['reservation_charges.id'], name=op.f('fk_invoice_items_charge_id_reservation_charges'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_items_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_items'))
    )
    op.create_index(op.f('ix_invoice_items_created_at'), 'invoice_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_created_at'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_service_order_items_order_id'), table_name='service_order_items')
    op.drop_index(op.f('ix_service_order_items_created_at'), table_name='service_order_items')
    op.drop_table('service_order_items')
    op.drop_index(op.f('ix_reservation_charges_service_date'), table_name='reservation_charges')
    op.drop_index(op.f('ix_reservation_charges_reservation_id'), table_name='reservation_charges')
    op.drop_index(op.f('ix_reservation_charges_posted_at'), table_name='reservation_charges')
    op.drop_index(op.f('ix_reservation_charges_is_voided'), table_name='reservation_charges')
    op.drop_index(op.f('ix_reservation_charges_created_at'), table_name='reservation_charges')
    op.drop_index(op.f('ix_reservation_charges_charge_type'), table_name='reservation_charges')
    op.drop_table('reservation_charges')
    op.drop_index('ix_payments_status_entry', table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_reservation_id'), table_name='payments')
    op.drop_index('ix_payments_reservation_entry', table_name='payments')
    op.drop_index('ix_payments_paid_at', table_name='payments')
    op.drop_index(op.f('ix_payments_number'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_guest_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_entry_type'), table_name='payments')
    op.drop_index(op.f('ix_payments_deleted_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_maintenance_tickets_ticket_number'), table_name='maintenance_tickets')
    op.drop_index(op.f('ix_maintenance_tickets_status'), table_name='maintenance_tickets')
    op.drop_index(op.f('ix_maintenance_tickets_room_id'), table_name='maintenance_tickets')
    op.drop_index(op.f('ix_maintenance_tickets_reported_at'), table_name='maintenance_tickets')
    op.drop_index(op.f('ix_maintenance_tickets_priority'), table_name='maintenance_tickets')
    op.drop_index(op.f('ix_maintenance_tickets_created_at'), table_name='maintenance_tickets')
    op.drop_index(op.f('ix_maintenance_tickets_category'), table_name='maintenance_tickets')
    op.drop_index(op.f('ix_maintenance_tickets_assigned_to_id'), table_name='maintenance_tickets')
    op.drop_index('ix_maintenance_status_priority', table_name='maintenance_tickets')
    op.drop_table('maintenance_tickets')
    op.drop_index('ix_service_orders_status_placed', table_name='service_orders')
    op.drop_index(op.f('ix_service_orders_status'), table_name='service_orders')
    op.drop_index(op.f('ix_service_orders_reservation_id'), table_name='service_orders')
    op.drop_index(op.f('ix_service_orders_placed_at'), table_name='service_orders')
    op.drop_index(op.f('ix_service_orders_order_type'), table_name='service_orders')
    op.drop_index(op.f('ix_service_orders_order_number'), table_name='service_orders')
    op.drop_index(op.f('ix_service_orders_is_billed'), table_name='service_orders')
    op.drop_index(op.f('ix_service_orders_deleted_at'), table_name='service_orders')
    op.drop_index(op.f('ix_service_orders_created_at'), table_name='service_orders')
    op.drop_table('service_orders')
    op.drop_index(op.f('ix_reservation_guests_reservation_id'), table_name='reservation_guests')
    op.drop_index(op.f('ix_reservation_guests_created_at'), table_name='reservation_guests')
    op.drop_table('reservation_guests')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_reservation_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_number'), table_name='invoices')
    op.drop_index('ix_invoices_issue_status', table_name='invoices')
    op.drop_index(op.f('ix_invoices_issue_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_guest_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_deleted_at'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_created_at'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_housekeeping_tasks_status'), table_name='housekeeping_tasks')
    op.drop_index(op.f('ix_housekeeping_tasks_scheduled_date'), table_name='housekeeping_tasks')
    op.drop_index(op.f('ix_housekeeping_tasks_room_id'), table_name='housekeeping_tasks')
    op.drop_index(op.f('ix_housekeeping_tasks_created_at'), table_name='housekeeping_tasks')
    op.drop_index(op.f('ix_housekeeping_tasks_assigned_to_id'), table_name='housekeeping_tasks')
    op.drop_index('ix_housekeeping_status_date', table_name='housekeeping_tasks')
    op.drop_index('ix_housekeeping_assignee_status', table_name='housekeeping_tasks')
    op.drop_table('housekeeping_tasks')
    op.drop_index(op.f('ix_check_outs_reservation_id'), table_name='check_outs')
    op.drop_index(op.f('ix_check_outs_created_at'), table_name='check_outs')
    op.drop_table('check_outs')
    op.drop_index(op.f('ix_check_ins_reservation_id'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_created_at'), table_name='check_ins')
    op.drop_table('check_ins')
    op.drop_table('room_amenity_links')
    op.drop_index('ix_reservations_status_window', table_name='reservations')
    op.drop_index(op.f('ix_reservations_status'), table_name='reservations')
    op.drop_index('ix_reservations_room_window', table_name='reservations')
    op.drop_index(op.f('ix_reservations_room_type_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_room_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_reference'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_payment_status'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_guest_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_deleted_at'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_created_at'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_check_out_date'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_check_in_date'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_table('user_roles')
    op.drop_index('ix_rooms_type_active', table_name='rooms')
    op.drop_index('ix_rooms_status_floor', table_name='rooms')
    op.drop_index(op.f('ix_rooms_status'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_room_type_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_number'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_deleted_at'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_created_at'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_table('room_type_amenities')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_created_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_created_at'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index('ix_notifications_user_read_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_dedupe_key'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_menu_items_deleted_at'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_created_at'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_category_id'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_login_attempts_email'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_created_at'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_attempted_at'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_inventory_movements_item_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_created_at'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_hotel_settings_key'), table_name='hotel_settings')
    op.drop_index(op.f('ix_hotel_settings_created_at'), table_name='hotel_settings')
    op.drop_table('hotel_settings')
    op.drop_index(op.f('ix_expenses_expense_number'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_deleted_at'), table_name='expenses')
    op.drop_index('ix_expenses_date_category', table_name='expenses')
    op.drop_index(op.f('ix_expenses_created_at'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('ix_audit_user_created', table_name='audit_logs')
    op.drop_index('ix_audit_resource_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_ip_address'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_users_status_deleted', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_services_deleted_at'), table_name='services')
    op.drop_index(op.f('ix_services_created_at'), table_name='services')
    op.drop_index(op.f('ix_services_category'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_room_types_deleted_at'), table_name='room_types')
    op.drop_index(op.f('ix_room_types_created_at'), table_name='room_types')
    op.drop_table('room_types')
    op.drop_index(op.f('ix_roles_deleted_at'), table_name='roles')
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_created_at'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_payment_methods_created_at'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_menu_categories_created_at'), table_name='menu_categories')
    op.drop_table('menu_categories')
    op.drop_index(op.f('ix_inventory_items_deleted_at'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_created_at'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_guests_reference'), table_name='guests')
    op.drop_index(op.f('ix_guests_phone'), table_name='guests')
    op.drop_index('ix_guests_name', table_name='guests')
    op.drop_index(op.f('ix_guests_last_name'), table_name='guests')
    op.drop_index(op.f('ix_guests_first_name'), table_name='guests')
    op.drop_index(op.f('ix_guests_email'), table_name='guests')
    op.drop_index(op.f('ix_guests_deleted_at'), table_name='guests')
    op.drop_index('ix_guests_deleted', table_name='guests')
    op.drop_index(op.f('ix_guests_created_at'), table_name='guests')
    op.drop_table('guests')
    op.drop_index(op.f('ix_amenities_created_at'), table_name='amenities')
    op.drop_table('amenities')
    # ### end Alembic commands ###
